Rename Internal SCAN Switchboard Mentions to SFS Switchboard
seattleflu/documentation pull request #43
Opened 2022-01-05 22:22 UTC by bencap

The SCAN Switchboard is now the SFS Switchboard. These changes update the project documentation to match this name change.

2022-01-06 00:48 UTC, bencap commented
![](https://github.trello.services/images/mini-trello-icon.png) [Rename internal mentions of "SCAN switchboard"](https://trello.com/c/hpw5yZOa/832-rename-internal-mentions-of-scan-switchboard)

2022-01-06 20:07 UTC, kschwabefry requested changes
Thanks for taking the time to update the docs as well. A few small comments below to update paths for consistency with other PRs.

2022-01-06 20:28 UTC, bencap commented on Deploying.md
> +* [SFS Switchboard](https://github.com/seattleflu/backoffice/tree/master/switchboard)
yup thanks for catching these!

2022-01-07 01:05 UTC, kschwabefry approved these changes

2022-01-10 23:37 UTC, merged